# -*- coding: utf-8 -*-
"""k-means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9Vh84C1gAuPLUGenMc-aWbm4K7_D2Og
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

df = pd.read_csv('iris.csv')
wscc = []

for x in range(1,11):
    kmeans = KMeans(n_clusters=x, init='k-means++', random_state=0)
    kmeans.fit(df[['sepal_length','sepal_width','petal_length','petal_width']])
    wscc.append(kmeans.inertia_)

plt.plot(range(1,11), wscc)
plt.title('Metodo del codo')
plt.xlabel('Numero de clusters')
plt.ylabel('WCSS')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

df = pd.read_csv('iris.csv')

x = df[['sepal_length','sepal_width','petal_length','petal_width']]


kmeans = KMeans(n_clusters=3, random_state=0)
y_kmeans = kmeans.fit_predict(x)

df['cluster'] = y_kmeans


plt.scatter(df['petal_length'], df['petal_width'], c=df['cluster'])
plt.xlabel('Longitud del pétalo')
plt.ylabel('Ancho del pétalo')
plt.title('Clustering de Iris con K-Means')
plt.show()